### ISSUE TITLE
[BUG] it seems that the extension is not working anymore using the Annotations

### ISSUE THREAD

**Issue by Simperfit** [gorghoa/ScenarioStateBehatExtension#35]
using the Annotations it seems that it is not working for exemple I get this error : 
```
  [Behat\Testwork\Argument\Exception\UnknownParameterValueException]                                                
  Can not find a matching value for an argument `$createdUsers` of the method `UserContext::iGetAnExistingUser()`.  
                                                                                                                    
```

With symfony 3.3, behat 3.3.1, api-platform 2.1

**Comment by gorghoa** [comment]
Thanks for your report @Simperfit, Can you post a more extensive code sample triggering the issue?

Does your class implements `ScenarioStateAwareContext`?

**Comment by gorghoa** [comment]
![image](https://user-images.githubusercontent.com/662768/30284243-a97f1a4a-971a-11e7-82a4-60d2ea187243.png)

**Comment by Simperfit** [comment]
It seems that there were another thing behind this issues, this seems to work now.

**Comment by gorghoa** [comment]
👍
